name: Bumpr
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled

permissions:
  # push tags
  contents: write

  # add comments to the pull request
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-bumpr@v1
