name: Bumpr
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-bumpr@v1
