name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-northeast-1
  APP_NAME: mastodon-jihou-bot

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go get .

      - name: build for lambda
        run: |
          GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap .

      - id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - id: build
        name: build
        run: |
          mkdir dist
          zip -r dist/main.zip bootstrap
          checksum="$(sha256sum dist/main.zip | awk '{ print $1 }')"
          echo "$checksum" > dist/"$version".checksum
          echo "checksum=$checksum" >> "$GITHUB_OUTPUT"

      - name: deploy to s3
        run: |
          aws s3 cp --recursive dist/ "s3://fohte-lambda-sources/$APP_NAME/"

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.APP_NAME }}.zip
          tag_name: ${{ steps.tag.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
