name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-northeast-1
  APP_NAME: mastodon-jihou-bot

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
          cache-dependency-path: go.sum

      - run: go get .

      - name: build for lambda
        run: |
          GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap .

      - id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy to s3
        run: |
          zip -r main.zip bootstrap
          aws s3api put-object \
            --bucket fohte-lambda-sources \
            --key "$APP_NAME"/latest.zip \
            --body main.zip

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.APP_NAME }}.zip
          tag_name: ${{ steps.tag.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: false
