name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: ap-northeast-1
  APP_NAME: mastodon-jihou-bot

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go get .

      - name: build for lambda
        run: |
          GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap .

      - id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - id: build
        name: build
        run: |
          mkdir dist
          zip -r dist/latest.zip bootstrap
          openssl dgst -sha256 -binary dist/latest.zip | base64 | tee dist/checksum-"$version".base64sha256
          {
            echo "list<<EOF"
            find dist -type f
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          version: ${{ steps.tag.outputs.version }}

      - name: deploy to s3
        run: |
          aws s3 cp --recursive dist/ "s3://fohte-lambda-sources/$APP_NAME/"

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build.outputs.list }}
          tag_name: ${{ steps.tag.outputs.version }}
          generate_release_notes: true
          draft: false
          # e.g. v1.2.3-rc.1, v1.2.3-alpha.1, v1.2.3-beta.1
          prerelease: ${{ contains(steps.tag.outputs.version, '-') }}
