name: Test

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: fohte/mastodon-jihou-bot
          identity: mastodon-jihou-bot-test
          domain: octo-sts.fohte.net

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          token: ${{ steps.octo-sts.outputs.token }}

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: generate and fmt
        run: |
          go install go.uber.org/mock/mockgen@latest
          go generate ./...
          go fmt ./...

      - run: go get .

      - id: auto-commit-auction
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_user_name: 'fohte-bot[bot]'
          commit_user_email: '139195068+fohte-bot[bot]@users.noreply.github.com'

      - name: 'Run if changes have been detected'
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          echo 'Changes detected. Committing and pushing to remote.'
          exit 1

      - name: Run tests
        run: go test -v ./...
