name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
          cache-dependency-path: go.sum

      - name: generate and fmt
        run: |
          go generate ./...
          go fmt ./...

      - run: go get .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: 'fohte-bot[bot]'
          commit_user_email: '139195068+fohte-bot[bot]@users.noreply.github.com'

      - name: 'Run if changes have been detected'
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          echo 'Changes detected. Committing and pushing to remote.'
          exit 1

      - name: Run tests
        run: go test -v ./...
